# Form implementation generated from reading ui file 'footer.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        self.navbar = QtWidgets.QFrame(parent=Form)
        self.navbar.setMinimumSize(QtCore.QSize(0, 0))
        self.navbar.setMaximumSize(QtCore.QSize(16777215, 90))
        self.navbar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.navbar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.navbar.setObjectName("navbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.navbar)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.navbar)
        self.frame.setMaximumSize(QtCore.QSize(100, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButtonSearch = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonSearch.setMaximumSize(QtCore.QSize(64, 64))
        self.pushButtonSearch.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButtonSearch.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Mediamodifier-Design.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSearch.setIcon(icon)
        self.pushButtonSearch.setIconSize(QtCore.QSize(64, 64))
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.verticalLayout_2.addWidget(self.pushButtonSearch)
        self.label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(241, 241, 241)")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.frame_2 = QtWidgets.QFrame(parent=self.navbar)
        self.frame_2.setMaximumSize(QtCore.QSize(100, 100))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButtonLibrary = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButtonLibrary.setMaximumSize(QtCore.QSize(64, 64))
        self.pushButtonLibrary.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButtonLibrary.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/whiote libraray.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLibrary.setIcon(icon1)
        self.pushButtonLibrary.setIconSize(QtCore.QSize(64, 64))
        self.pushButtonLibrary.setObjectName("pushButtonLibrary")
        self.verticalLayout_3.addWidget(self.pushButtonLibrary)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(241, 241, 241);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Search"))
        self.label_2.setText(_translate("Form", "Your Library"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
