# Form implementation generated from reading ui file 'playListWidget3.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Playlist(object):
    def setupUi(self, Form):
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PlaylistWidget = QtWidgets.QFrame(parent=Form)
        self.PlaylistWidget.setMaximumSize(QtCore.QSize(16777215, 128))
        self.PlaylistWidget.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.PlaylistWidget.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.PlaylistWidget.setObjectName("PlaylistWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.PlaylistWidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.framePic = QtWidgets.QFrame(parent=self.PlaylistWidget)
        self.framePic.setMaximumSize(QtCore.QSize(80, 80))
        self.framePic.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.framePic.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.framePic.setObjectName("framePic")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.framePic)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pic1 = QtWidgets.QLabel(parent=self.framePic)
        self.pic1.setMaximumSize(QtCore.QSize(64, 64))
        self.pic1.setText("")
        self.pic1.setPixmap(QtGui.QPixmap(":/images/deafult Playlist pic.png"))
        self.pic1.setScaledContents(True)
        self.pic1.setObjectName("pic1")
        self.horizontalLayout_5.addWidget(self.pic1)
        self.horizontalLayout_4.addWidget(self.framePic)
        self.frame_4 = QtWidgets.QFrame(parent=self.PlaylistWidget)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(202, 202, 202);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(202, 202, 202);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.songNum1 = QtWidgets.QFrame(parent=self.PlaylistWidget)
        self.songNum1.setMinimumSize(QtCore.QSize(120, 0))
        self.songNum1.setMaximumSize(QtCore.QSize(100, 64))
        self.songNum1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.songNum1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.songNum1.setObjectName("songNum1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.songNum1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(parent=self.songNum1)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(202, 202, 202);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.label_3 = QtWidgets.QLabel(parent=self.songNum1)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.horizontalLayout_4.addWidget(self.songNum1)
        self.verticalLayout.addWidget(self.PlaylistWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Playlist name"))
        self.label_5.setText(_translate("Form", "Artist"))
        self.label_6.setText(_translate("Form", "##### Songs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
