
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        self.playlistImportFrame = QtWidgets.QFrame(parent=Form)
        self.playlistImportFrame.setGeometry(QtCore.QRect(180, 180, 401, 201))
        self.playlistImportFrame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.playlistImportFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.playlistImportFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.playlistImportFrame.setObjectName("playlistImportFrame")
        self.importFrameLayout = QtWidgets.QVBoxLayout(self.playlistImportFrame)
        self.importFrameLayout.setObjectName("importFrameLayout")
        self.newPlaylistFrame = QtWidgets.QFrame(parent=self.playlistImportFrame)
        self.newPlaylistFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.newPlaylistFrame.setAutoFillBackground(False)
        self.newPlaylistFrame.setStyleSheet("background-color: rgb(26, 26, 26);")
        self.newPlaylistFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.newPlaylistFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.newPlaylistFrame.setObjectName("newPlaylistFrame")
        self.newPlaylistFrameLayout = QtWidgets.QHBoxLayout(self.newPlaylistFrame)
        self.newPlaylistFrameLayout.setSpacing(16)
        self.newPlaylistFrameLayout.setObjectName("newPlaylistFrameLayout")
        self.newPlaylistFrameIcon = QtWidgets.QLabel(parent=self.newPlaylistFrame)
        self.newPlaylistFrameIcon.setMaximumSize(QtCore.QSize(64, 64))
        self.newPlaylistFrameIcon.setText("")
        self.newPlaylistFrameIcon.setPixmap(QtGui.QPixmap("musicNote.svg"))
        self.newPlaylistFrameIcon.setScaledContents(True)
        self.newPlaylistFrameIcon.setObjectName("newPlaylistFrameIcon")
        self.newPlaylistFrameLayout.addWidget(self.newPlaylistFrameIcon)
        self.newPlaylistFrameTxt = QtWidgets.QLabel(parent=self.newPlaylistFrame)
        self.newPlaylistFrameTxt.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.newPlaylistFrameTxt.setFont(font)
        self.newPlaylistFrameTxt.setStyleSheet("color: rgb(202, 202, 202);")
        self.newPlaylistFrameTxt.setObjectName("newPlaylistFrameTxt")
        self.newPlaylistFrameLayout.addWidget(self.newPlaylistFrameTxt)
        self.importFrameLayout.addWidget(self.newPlaylistFrame)
        self.importPlaylistFrame = QtWidgets.QFrame(parent=self.playlistImportFrame)
        self.importPlaylistFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.importPlaylistFrame.setAutoFillBackground(False)
        self.importPlaylistFrame.setStyleSheet("background-color: rgb(26, 26, 26);")
        self.importPlaylistFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.importPlaylistFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.importPlaylistFrame.setObjectName("importPlaylistFrame")
        self.importPlaylistFrameLayout = QtWidgets.QHBoxLayout(self.importPlaylistFrame)
        self.importPlaylistFrameLayout.setSpacing(16)
        self.importPlaylistFrameLayout.setObjectName("importPlaylistFrameLayout")
        self.importPlaylistFrameIcon = QtWidgets.QLabel(parent=self.importPlaylistFrame)
        self.importPlaylistFrameIcon.setMaximumSize(QtCore.QSize(64, 64))
        self.importPlaylistFrameIcon.setText("")
        self.importPlaylistFrameIcon.setPixmap(QtGui.QPixmap("import.svg"))
        self.importPlaylistFrameIcon.setScaledContents(True)
        self.importPlaylistFrameIcon.setObjectName("importPlaylistFrameIcon")
        self.importPlaylistFrameLayout.addWidget(self.importPlaylistFrameIcon)
        self.importPlaylistFrameTxt = QtWidgets.QLabel(parent=self.importPlaylistFrame)
        self.importPlaylistFrameTxt.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.importPlaylistFrameTxt.setFont(font)
        self.importPlaylistFrameTxt.setStyleSheet("color: rgb(202, 202, 202);")
        self.importPlaylistFrameTxt.setObjectName("importPlaylistFrameTxt")
        self.importPlaylistFrameLayout.addWidget(self.importPlaylistFrameTxt)
        self.importFrameLayout.addWidget(self.importPlaylistFrame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.newPlaylistFrameTxt.setText(_translate("Form", "Create a new playlist"))
        self.importPlaylistFrameTxt.setText(_translate("Form", "Import a spotify playlist"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
